%% Parsing KT-airfoil data post-process: variational reconstruction (05/15/2026)
clc; clear; close all;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
parent_dir_str = 'SENSEI_POSTPROCESSING';
path_parts = regexp(mfilename('fullpath'), filesep, 'split');
path_idx = find(cellfun(@(s1)strcmp(s1,parent_dir_str),path_parts));
parent_dir = fullfile(path_parts{1:path_idx});
addpath(genpath(parent_dir));
clear parent_dir_str path_idx path_parts
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clc;
DATA_DIR='C:\Users\wajordan\Desktop\git_MATLAB\SENSEI_POSTPROCESSING\new_scripts_04_2026\data_preprocess';
file_name = 'F_ALL_05_16_2026.mat';
load(fullfile(DATA_DIR,file_name));

% DATA_DIR='C:\Users\wajordan\Desktop\CASES\';
% foldernames1 = {};
% foldernames1 = [foldernames1,'ALPHA_5_JOUKOWSKI_C_GRID_curved_2026-01-15_02.00.10_CURVED_P4_q6_q6_hoex_TT_BC_VARLAY2_ITER2000_IC10'];% 1
% foldernames1 = [foldernames1,'ALPHA_5_JOUKOWSKI_C_GRID_curved_2026-01-15_03.10.03_CURVED_P4_q6_q6_hoex_TT_BC_VARLAY8_ITER2000_IC10'];% 2
% foldernames1 = [foldernames1,'ALPHA_5_JOUKOWSKI_C_GRID_curved_2026-02-13_12.01.06_ORDER_4_bc_IC_10_100_iter_GEO4'];% 3
% foldernames1 = [foldernames1,'ALPHA_5_JOUKOWSKI_C_GRID_curved_limited_2026-02-13_12.00.09_ORDER_4_bc_IC_10_100_iter_GEO4'];% 4
% foldernames1 = [foldernames1,'JOUKOWSKI_C_GRID_curved_04_01_2026-04-02_12.20.09'];        % 5
% foldernames1 = [foldernames1,'JOUKOWSKI_C_GRID_curved_04_01_regress_2026-04-02_12.21.04'];% 6

folders = [1,1,...
           1,1,...
           2,2];
prim = {'primal','primal',...
        'ic','ic',...
        'ic','ic'};
geom = {'linear','curved',...
        'linear','curved',...
        'linear','curved'};
legend_labels = {'$C_L$ Primal','$C_L$ Primal (reconstructed)',...
                 '$C_L$ ETE (k-exact)','$C_L$ ETE (k-exact, reconstructed)',...
                 '$C_L$ ETE (CWENO)','$C_L$ ETE (CWENO, reconstructed)'};
linspec ={'-','--',...
          '-','--',...
          '-','--'};
colors  = reshape([lines(3),lines(3)].',3,[]).';
markers = {'^','^',...
           '^','^',...
           'o','o'};
marker_size = [9,9, 9,9, 9,9];
var = {'CL','CL',...
       'CL','CL',...
       'CL','CL'};
ics = {[0],[0],...
       [0],[0],...
       [0],[0]};

[N,E,OOA] = gather_error_plot_data(ALL_DATA,folders,geom,prim,var,ics);
post_plot_commands = {"set(hfig.Children(4),'Ylim',[1e-6,1e0]);",...
                      "yticks(hfig.Children(4),10.^(-6:1:0));",  ...
                      "set(hfig.Children(4),'Xlim',[10,1000])",    ...
                      "set(hfig.Children(3),'Location','southwest');",...
                      "set(hfig.Children(2),'Ylim',[0,5]);",...
                      "set(hfig.Children(2),'Xlim',[10,1000]);",...
                      "set(hfig.Children(1),'Location','southwest');"};
x_label1 = '$N_{cells}^{1/2}$';
x_label2 = x_label1;
y_label1 ='Error';
y_label2 ='OOA';
hfig = plot_OOA(N,E,OOA,linspec,colors,markers,marker_size,x_label1,y_label1,x_label2,y_label2,legend_labels,post_plot_commands);
hold off