function [hfig,p] = plot_OOA(N,E,OOA,linspec,colors,markers,marker_size,x_label1,y_label1,x_label2,y_label2,legend_labels,post_plot_commands)
minN = min(cellfun(@min,N));
maxN = max(cellfun(@max,N));
lim1 = 10^( floor( log10( minN   ) ) );
lim2 = 10^( ceil(  log10( maxN ) ) );

hfig = stdplot(1);
p = struct();
p.s1 = struct();
p.s1.sp = subplot(1,2,1);
p.s1.p1 = struct();
p.s1.p2 = struct();
hold on
for i = 1:numel(E)
    ptmp = plot( nan*N{i},nan*E{i}(1,:),...
                        MarkerSize=sqrt(marker_size(i)),...
                        Marker=markers{i},...
                        MarkerEdgeColor=colors(i,:),...
                        Color=[colors(i,:),1],...
                        LineStyle=linspec{i});
    if (size(E{i},1)>1)
        N_ic = size(E{i},1);
        p.s1.p1(i).p = struct();
        p.s1.p2(i).p = struct();
        for j = 1:N_ic
            alpha = alpha_calc( j/N_ic );    
            p.s1.p1(i).p(j) = plot( N{i}, E{i}(j,:),...
                                    Color=[colors(i,:),alpha],...
                                    LineStyle=linspec{i},...
                                    HandleVisibility='off');
            p.s1.p2(i).p(j) = scatter( N{i}, E{i}(j,:),...
                                    marker_size(i),...
                                    markers{i},...
                                    MarkerEdgeColor=colors(i,:),...
                                    MarkerEdgeAlpha=alpha,...
                                    LineWidth=p.s1.p1(i).p(j).LineWidth,...
                                    HandleVisibility='off');
        end
    else
        p.s1.p1(i).p  = plot( N{i}, E{i}(1,:),...
                              Color=[colors(i,:),1],...
                              LineStyle=linspec{i},...
                              HandleVisibility='off');
        p.s1.p2(i).p = scatter( N{i}, E{i}(1,:),...
                                marker_size(i),...
                                markers{i},...
                                MarkerEdgeColor=colors(i,:),...
                                MarkerEdgeAlpha=1,...
                                LineWidth=p.s1.p1(i).p.LineWidth,...
                                HandleVisibility='off');
    end
    % plot(N,E{i},markers{i},MarkerSize=marker_size)
end
xlim([lim1,lim2])
xlabel(x_label1,Interpreter="latex");
ylabel(y_label1,Interpreter="latex");
p.s1.l = legend(legend_labels,Interpreter="latex");
p.s1.l.ItemTokenSize = [22,0];
set(gca,'Yscale','log')
set(gca,'Xscale','log')


p.s2 = struct();
p.s2.sp = subplot(1,2,2);
p.s2.p1 = struct();
p.s2.p2 = struct();
hold on
for i = 1:numel(OOA)
    ptmp = plot( nan*N{i},nan*OOA{i}(1,:),...
                        MarkerSize=sqrt(marker_size(i)),...
                        Marker=markers{i},...
                        MarkerEdgeColor=colors(i,:),...
                        Color=[colors(i,:),1],...
                        LineStyle=linspec{i});
    if (size(OOA{i},1)>1)
        N_ic = size(OOA{i},1);
        p.s2.p1(i).p = struct();
        p.s2.p2(i).p = struct();
        for j = 1:N_ic
            alpha = alpha_calc( j/N_ic );    
            p.s2.p1(i).p(j) = plot( N{i}, OOA{i}(j,:),...
                                    Color=[colors(i,:),alpha],...
                                    LineStyle=linspec{i},...
                                    HandleVisibility='off');
            p.s2.p2(i).p(j) = scatter( N{i}, OOA{i}(j,:),...
                                    marker_size(i),...
                                    markers{i},...
                                    MarkerEdgeColor=colors(i,:),...
                                    MarkerEdgeAlpha=alpha,...
                                    LineWidth=p.s2.p1(i).p(j).LineWidth,...
                                    HandleVisibility='off');
        end
    else
        p.s2.p1(i).p  = plot( N{i}, OOA{i}(1,:),...
                              Color=[colors(i,:),1],...
                              LineStyle=linspec{i},...
                              HandleVisibility='off');
        p.s2.p2(i).p = scatter( N{i}, OOA{i}(1,:),...
                                marker_size(i),...
                                markers{i},...
                                MarkerEdgeColor=colors(i,:),...
                                MarkerEdgeAlpha=1,...
                                LineWidth=p.s2.p1(i).p.LineWidth, ...
                                HandleVisibility='off');
    end
    % plot(N,OOA{i},markers{i},MarkerSize=marker_size)
end
xlim([lim1,lim2])
xlabel(x_label2,Interpreter="latex");
ylabel(y_label2,Interpreter="latex");
p.s2.l = legend(legend_labels,Interpreter="latex");
p.s2.l.ItemTokenSize = [22,0];
set(gca,'Xscale','log')
cellfun(@eval,post_plot_commands)
end

function alpha = alpha_calc(x)
min_alpha = 0.1;
max_alpha = 0.25;
alpha = min_alpha + (max_alpha-min_alpha)*sqrt(x);
% alpha = min_alpha + (1-min_alpha)*(2*x-1).^2;
end

function hfig = stdplot(i)
fontsize  = 6;%14;
linewidth = 1;%2;
% fontsize  = 20;
% linewidth = 2;
hfig=figure(i);
clf(hfig);
dim = [7.5 5.5 6.25 2.5];
set(hfig,'Units','Inches','Position',dim);
set(hfig,'DefaultAxesFontName','Helvetica');
set(hfig,'DefaultTextFontName','Helvetica'); 
set(hfig,'DefaultAxesFontSize',fontsize);
set(hfig,'DefaultTextFontSize',fontsize);
set(hfig,'PaperUnits',get(gcf,'Units'));
pos = get(hfig,'Position');
set(hfig,'PaperPosition',[0 0 pos(3) pos(4)]);
set(gca,'Units','Inches');
set(hfig,'DefaultLineLineWidth',linewidth)
set(hfig,'DefaultLineLineWidth',linewidth)

end